## XGBoost v2

- Same model as XGBoost v1, but with more feature engineering
- Resulted in a 0.001 increase in accuracy

In [1]:
from dotenv import load_dotenv
import kagglehub
from pathlib import Path
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report
import torch
from xgboost import XGBClassifier

if torch.cuda.is_available():
    device="cuda"
else:
    device="cpu"
device

'cuda'

In [2]:
load_dotenv()

if not Path("../Data/.complete/competitions/playground-series-s6e6/bundle.complete").is_file():
    kagglehub.competition_download("playground-series-s6e6", output_dir="Data")
    print("Data downloaded")
else:
    print("Data not downloaded, already exists")

Data not downloaded, already exists

In [3]:
train = pd.read_csv("../Data/train.csv", index_col="id")
train.head()

,alpha,delta,u,g,r,i,z,redshift,spectral_type,galaxy_population,class
id,,,,,,,,,,,
0,147.734256,16.959273,25.472123,21.895559,20.357926,19.257113,18.621057,0.408982,M,Red_Sequence,GALAXY
1,127.988677,32.346716,20.778509,19.087062,17.587208,17.226067,16.786433,0.157976,M,Red_Sequence,GALAXY
2,179.792648,35.344843,21.035203,21.079128,21.171840,20.582629,20.557366,2.823770,O/B,Blue_Cloud,QSO
3,225.818295,48.569421,23.305056,21.050736,19.017754,18.365658,17.914952,0.536099,M,Red_Sequence,GALAXY
4,141.836135,19.342852,21.703158,19.471680,18.234449,17.899447,17.616185,0.555761,M,Red_Sequence,GALAXY

In [7]:
def add_features(df):
    df = df.copy()

    bands = ['u', 'g', 'r', 'i', 'z']

    # mag stats
    df['mag_mean'] = df[bands].mean(axis=1)
    df['mag_std'] = df[bands].std(axis=1)
    df['mag_max'] = df[bands].max(axis=1)
    df['mag_min'] = df[bands].min(axis=1)
    df['mag_range'] = df['mag_max'] - df['mag_min']

    # color indices
    df['u_g'] = df['u'] - df['g']
    df['g_r'] = df['g'] - df['r']
    df['r_i'] = df['r'] - df['i']
    df['i_z'] = df['i'] - df['z']
    df['u_r'] = df['u'] - df['r']
    df['u_i'] = df['u'] - df['i']
    df['u_z'] = df['u'] - df['z']
    df['g_i'] = df['g'] - df['i']
    df['g_z'] = df['g'] - df['z']
    df['r_z'] = df['r'] - df['z']

    # spatial trigonometry
    alpha_rad = np.radians(df["alpha"])
    delta_rad = np.radians(df["delta"])
    df["alpha_sin"] = np.sin(alpha_rad)
    df["alpha_cos"] = np.cos(alpha_rad)
    df["delta_sin"] = np.sin(delta_rad)
    df["delta_cos"] = np.cos(delta_rad)

    # redshift interactions
    epsilon = 1e-5
    abs_redshift = df['redshift'].abs() + epsilon
    for col in ['u_g', 'g_r', 'r_i', 'i_z']:
        df[f'{col}_per_redshift'] = df[col] / abs_redshift
    for b in bands:
        df[f'redshift_{b}'] = df['redshift'] * df[b]
    
    return df

In [12]:
X = add_features(train).drop(columns=["class"])
categorical_cols = ["spectral_type", "galaxy_population"]
for col in categorical_cols:
    X[col] = X[col].astype("category")

le = LabelEncoder()
y = le.fit_transform(train["class"])

X_train, X_val, y_train, y_val = train_test_split(
    X, 
    y, 
    test_size=0.2,
    random_state=42, 
    stratify=y
)
print(f'Features: {X_train.shape[1]}')

Features: 38

In [11]:
model = XGBClassifier(
    device=device,
    random_state=42,
    n_estimators=2000,
    learning_rate=0.05,
    max_depth=5,
    early_stopping_rounds=100,
    enable_categorical=True
)

model.fit(
    X_train,
    y_train,
    eval_set=[(X_val, y_val)]
)

preds = model.predict(X_val)

print("Accuracy:", accuracy_score(y_val, preds))
print(classification_report(y_val, preds, target_names=le.classes_))

[0]	validation_0-mlogloss:0.82030
[1]	validation_0-mlogloss:0.76877
[2]	validation_0-mlogloss:0.72330
[3]	validation_0-mlogloss:0.68276
[4]	validation_0-mlogloss:0.64616
[5]	validation_0-mlogloss:0.61288
[6]	validation_0-mlogloss:0.58234
[7]	validation_0-mlogloss:0.55446
[8]	validation_0-mlogloss:0.52871
[9]	validation_0-mlogloss:0.50495
[10]	validation_0-mlogloss:0.48298
[11]	validation_0-mlogloss:0.46258
[12]	validation_0-mlogloss:0.44360
[13]	validation_0-mlogloss:0.42582
[14]	validation_0-mlogloss:0.40927
[15]	validation_0-mlogloss:0.39379
[16]	validation_0-mlogloss:0.37930
[17]	validation_0-mlogloss:0.36574
[18]	validation_0-mlogloss:0.35293
[19]	validation_0-mlogloss:0.34087
[20]	validation_0-mlogloss:0.32964
[21]	validation_0-mlogloss:0.31884
[22]	validation_0-mlogloss:0.30887
[23]	validation_0-mlogloss:0.29932
[24]	validation_0-mlogloss:0.29032
[25]	validation_0-mlogloss:0.28189
[26]	validation_0-mlogloss:0.27379
[27]	validation_0-mlogloss:0.26625
[28]	validation_0-mlogloss:0.25915
[29]	validation_0-mlogloss:0.25239
[30]	validation_0-mlogloss:0.24594
[31]	validation_0-mlogloss:0.23986
[32]	validation_0-mlogloss:0.23411
[33]	validation_0-mlogloss:0.22868
[34]	validation_0-mlogloss:0.22350
[35]	validation_0-mlogloss:0.21860
[36]	validation_0-mlogloss:0.21397
[37]	validation_0-mlogloss:0.20961
[38]	validation_0-mlogloss:0.20531
[39]	validation_0-mlogloss:0.20135
[40]	validation_0-mlogloss:0.19736
[41]	validation_0-mlogloss:0.19373
[42]	validation_0-mlogloss:0.19023
[43]	validation_0-mlogloss:0.18681
[44]	validation_0-mlogloss:0.18368
[45]	validation_0-mlogloss:0.18055
[46]	validation_0-mlogloss:0.17772
[47]	validation_0-mlogloss:0.17487
[48]	validation_0-mlogloss:0.17212
[49]	validation_0-mlogloss:0.16951
[50]	validation_0-mlogloss:0.16715
[51]	validation_0-mlogloss:0.16496
[52]	validation_0-mlogloss:0.16283
[53]	validation_0-mlogloss:0.16082
[54]	validation_0-mlogloss:0.15890
[55]	validation_0-mlogloss:0.15691
[56]	validation_0-mlogloss:0.15514
[57]	validation_0-mlogloss:0.15331
[58]	validation_0-mlogloss:0.15154
[59]	validation_0-mlogloss:0.15002
[60]	validation_0-mlogloss:0.14856
[61]	validation_0-mlogloss:0.14715
[62]	validation_0-mlogloss:0.14581
[63]	validation_0-mlogloss:0.14441
[64]	validation_0-mlogloss:0.14309
[65]	validation_0-mlogloss:0.14182
[66]	validation_0-mlogloss:0.14071
[67]	validation_0-mlogloss:0.13960
[68]	validation_0-mlogloss:0.13849
[69]	validation_0-mlogloss:0.13748
[70]	validation_0-mlogloss:0.13652
[71]	validation_0-mlogloss:0.13563
[72]	validation_0-mlogloss:0.13471
[73]	validation_0-mlogloss:0.13389
[74]	validation_0-mlogloss:0.13309
[75]	validation_0-mlogloss:0.13234
[76]	validation_0-mlogloss:0.13159
[77]	validation_0-mlogloss:0.13085
[78]	validation_0-mlogloss:0.13013
[79]	validation_0-mlogloss:0.12938
[80]	validation_0-mlogloss:0.12871
[81]	validation_0-mlogloss:0.12812
[82]	validation_0-mlogloss:0.12753
[83]	validation_0-mlogloss:0.12694
[84]	validation_0-mlogloss:0.12638
[85]	validation_0-mlogloss:0.12588
[86]	validation_0-mlogloss:0.12530
[87]	validation_0-mlogloss:0.12485
[88]	validation_0-mlogloss:0.12437
[89]	validation_0-mlogloss:0.12392
[90]	validation_0-mlogloss:0.12332
[91]	validation_0-mlogloss:0.12293
[92]	validation_0-mlogloss:0.12244
[93]	validation_0-mlogloss:0.12205
[94]	validation_0-mlogloss:0.12168
[95]	validation_0-mlogloss:0.12134
[96]	validation_0-mlogloss:0.12084
[97]	validation_0-mlogloss:0.12052
[98]	validation_0-mlogloss:0.12022
[99]	validation_0-mlogloss:0.11983
[100]	validation_0-mlogloss:0.11954
[101]	validation_0-mlogloss:0.11919
[102]	validation_0-mlogloss:0.11886
[103]	validation_0-mlogloss:0.11849
[104]	validation_0-mlogloss:0.11819
[105]	validation_0-mlogloss:0.11783
[106]	validation_0-mlogloss:0.11754
[107]	validation_0-mlogloss:0.11730
[108]	validation_0-mlogloss:0.11692
[109]	validation_0-mlogloss:0.11665
[110]	validation_0-mlogloss:0.11638
[111]	validation_0-mlogloss:0.11610
[112]	validation_0-mlogloss:0.11575
[113]	validation_0-mlogloss:0.11552
[114]	validation_0-mlogloss:0.11519
[115]	validation_0-mlogloss:0.11499
[116]	validation_0-mlogloss:0.11477
[117]	validation_0-mlogloss:0.11455
[118]	validation_0-mlogloss:0.11427
[119]	validation_0-mlogloss:0.11407
[120]	validation_0-mlogloss:0.11391
[121]	validation_0-mlogloss:0.11373
[122]	validation_0-mlogloss:0.11348
[123]	validation_0-mlogloss:0.11331
[124]	validation_0-mlogloss:0.11314
[125]	validation_0-mlogloss:0.11297
[126]	validation_0-mlogloss:0.11279
[127]	validation_0-mlogloss:0.11254
[128]	validation_0-mlogloss:0.11232
[129]	validation_0-mlogloss:0.11213
[130]	validation_0-mlogloss:0.11199
[131]	validation_0-mlogloss:0.11179
[132]	validation_0-mlogloss:0.11160
[133]	validation_0-mlogloss:0.11143
[134]	validation_0-mlogloss:0.11127
[135]	validation_0-mlogloss:0.11115
[136]	validation_0-mlogloss:0.11098
[137]	validation_0-mlogloss:0.11087
[138]	validation_0-mlogloss:0.11072
[139]	validation_0-mlogloss:0.11057
[140]	validation_0-mlogloss:0.11046
[141]	validation_0-mlogloss:0.11032
[142]	validation_0-mlogloss:0.11017
[143]	validation_0-mlogloss:0.10996
[144]	validation_0-mlogloss:0.10984
[145]	validation_0-mlogloss:0.10968
[146]	validation_0-mlogloss:0.10959
[147]	validation_0-mlogloss:0.10945
[148]	validation_0-mlogloss:0.10930
[149]	validation_0-mlogloss:0.10916
[150]	validation_0-mlogloss:0.10908
[151]	validation_0-mlogloss:0.10894
[152]	validation_0-mlogloss:0.10886
[153]	validation_0-mlogloss:0.10875
[154]	validation_0-mlogloss:0.10862
[155]	validation_0-mlogloss:0.10854
[156]	validation_0-mlogloss:0.10843
[157]	validation_0-mlogloss:0.10833
[158]	validation_0-mlogloss:0.10822
[159]	validation_0-mlogloss:0.10813
[160]	validation_0-mlogloss:0.10802
[161]	validation_0-mlogloss:0.10793
[162]	validation_0-mlogloss:0.10787
[163]	validation_0-mlogloss:0.10775
[164]	validation_0-mlogloss:0.10768
[165]	validation_0-mlogloss:0.10755
[166]	validation_0-mlogloss:0.10746
[167]	validation_0-mlogloss:0.10740
[168]	validation_0-mlogloss:0.10728
[169]	validation_0-mlogloss:0.10717
[170]	validation_0-mlogloss:0.10711
[171]	validation_0-mlogloss:0.10706
[172]	validation_0-mlogloss:0.10698
[173]	validation_0-mlogloss:0.10690
[174]	validation_0-mlogloss:0.10679
[175]	validation_0-mlogloss:0.10671
[176]	validation_0-mlogloss:0.10664
[177]	validation_0-mlogloss:0.10657
[178]	validation_0-mlogloss:0.10652
[179]	validation_0-mlogloss:0.10647
[180]	validation_0-mlogloss:0.10639
[181]	validation_0-mlogloss:0.10633
[182]	validation_0-mlogloss:0.10626
[183]	validation_0-mlogloss:0.10616
[184]	validation_0-mlogloss:0.10611
[185]	validation_0-mlogloss:0.10599
[186]	validation_0-mlogloss:0.10591
[187]	validation_0-mlogloss:0.10588
[188]	validation_0-mlogloss:0.10578
[189]	validation_0-mlogloss:0.10565
[190]	validation_0-mlogloss:0.10561
[191]	validation_0-mlogloss:0.10554
[192]	validation_0-mlogloss:0.10545
[193]	validation_0-mlogloss:0.10536
[194]	validation_0-mlogloss:0.10533
[195]	validation_0-mlogloss:0.10524
[196]	validation_0-mlogloss:0.10518
[197]	validation_0-mlogloss:0.10509
[198]	validation_0-mlogloss:0.10501
[199]	validation_0-mlogloss:0.10498
[200]	validation_0-mlogloss:0.10489
[201]	validation_0-mlogloss:0.10485
[202]	validation_0-mlogloss:0.10480
[203]	validation_0-mlogloss:0.10475
[204]	validation_0-mlogloss:0.10464
[205]	validation_0-mlogloss:0.10458
[206]	validation_0-mlogloss:0.10453
[207]	validation_0-mlogloss:0.10447
[208]	validation_0-mlogloss:0.10441
[209]	validation_0-mlogloss:0.10437
[210]	validation_0-mlogloss:0.10433
[211]	validation_0-mlogloss:0.10423
[212]	validation_0-mlogloss:0.10420
[213]	validation_0-mlogloss:0.10412
[214]	validation_0-mlogloss:0.10408
[215]	validation_0-mlogloss:0.10402
[216]	validation_0-mlogloss:0.10393
[217]	validation_0-mlogloss:0.10386
[218]	validation_0-mlogloss:0.10380
[219]	validation_0-mlogloss:0.10374
[220]	validation_0-mlogloss:0.10371
[221]	validation_0-mlogloss:0.10364
[222]	validation_0-mlogloss:0.10360
[223]	validation_0-mlogloss:0.10353
[224]	validation_0-mlogloss:0.10348
[225]	validation_0-mlogloss:0.10345
[226]	validation_0-mlogloss:0.10339
[227]	validation_0-mlogloss:0.10334
[228]	validation_0-mlogloss:0.10326
[229]	validation_0-mlogloss:0.10321
[230]	validation_0-mlogloss:0.10315
[231]	validation_0-mlogloss:0.10309
[232]	validation_0-mlogloss:0.10301
[233]	validation_0-mlogloss:0.10296
[234]	validation_0-mlogloss:0.10289
[235]	validation_0-mlogloss:0.10286
[236]	validation_0-mlogloss:0.10282
[237]	validation_0-mlogloss:0.10279
[238]	validation_0-mlogloss:0.10269
[239]	validation_0-mlogloss:0.10267
[240]	validation_0-mlogloss:0.10256
[241]	validation_0-mlogloss:0.10251
[242]	validation_0-mlogloss:0.10247
[243]	validation_0-mlogloss:0.10241
[244]	validation_0-mlogloss:0.10236
[245]	validation_0-mlogloss:0.10231
[246]	validation_0-mlogloss:0.10226
[247]	validation_0-mlogloss:0.10224
[248]	validation_0-mlogloss:0.10215
[249]	validation_0-mlogloss:0.10209
[250]	validation_0-mlogloss:0.10206
[251]	validation_0-mlogloss:0.10202
[252]	validation_0-mlogloss:0.10198
[253]	validation_0-mlogloss:0.10193
[254]	validation_0-mlogloss:0.10187
[255]	validation_0-mlogloss:0.10182
[256]	validation_0-mlogloss:0.10179
[257]	validation_0-mlogloss:0.10171
[258]	validation_0-mlogloss:0.10165
[259]	validation_0-mlogloss:0.10162
[260]	validation_0-mlogloss:0.10157
[261]	validation_0-mlogloss:0.10154
[262]	validation_0-mlogloss:0.10148
[263]	validation_0-mlogloss:0.10145
[264]	validation_0-mlogloss:0.10142
[265]	validation_0-mlogloss:0.10138
[266]	validation_0-mlogloss:0.10134
[267]	validation_0-mlogloss:0.10131
[268]	validation_0-mlogloss:0.10127
[269]	validation_0-mlogloss:0.10123
[270]	validation_0-mlogloss:0.10117
[271]	validation_0-mlogloss:0.10112
[272]	validation_0-mlogloss:0.10106
[273]	validation_0-mlogloss:0.10099
[274]	validation_0-mlogloss:0.10090
[275]	validation_0-mlogloss:0.10085
[276]	validation_0-mlogloss:0.10080
[277]	validation_0-mlogloss:0.10074
[278]	validation_0-mlogloss:0.10070
[279]	validation_0-mlogloss:0.10066
[280]	validation_0-mlogloss:0.10061
[281]	validation_0-mlogloss:0.10057
[282]	validation_0-mlogloss:0.10051
[283]	validation_0-mlogloss:0.10048
[284]	validation_0-mlogloss:0.10043
[285]	validation_0-mlogloss:0.10041
[286]	validation_0-mlogloss:0.10036
[287]	validation_0-mlogloss:0.10030
[288]	validation_0-mlogloss:0.10027
[289]	validation_0-mlogloss:0.10025
[290]	validation_0-mlogloss:0.10018
[291]	validation_0-mlogloss:0.10015
[292]	validation_0-mlogloss:0.10008
[293]	validation_0-mlogloss:0.10006
[294]	validation_0-mlogloss:0.10002
[295]	validation_0-mlogloss:0.09995
[296]	validation_0-mlogloss:0.09992
[297]	validation_0-mlogloss:0.09986
[298]	validation_0-mlogloss:0.09983
[299]	validation_0-mlogloss:0.09977
[300]	validation_0-mlogloss:0.09974
[301]	validation_0-mlogloss:0.09968
[302]	validation_0-mlogloss:0.09965
[303]	validation_0-mlogloss:0.09962
[304]	validation_0-mlogloss:0.09958
[305]	validation_0-mlogloss:0.09957
[306]	validation_0-mlogloss:0.09952
[307]	validation_0-mlogloss:0.09948
[308]	validation_0-mlogloss:0.09940
[309]	validation_0-mlogloss:0.09936
[310]	validation_0-mlogloss:0.09932
[311]	validation_0-mlogloss:0.09925
[312]	validation_0-mlogloss:0.09922
[313]	validation_0-mlogloss:0.09918
[314]	validation_0-mlogloss:0.09916
[315]	validation_0-mlogloss:0.09911
[316]	validation_0-mlogloss:0.09909
[317]	validation_0-mlogloss:0.09906
[318]	validation_0-mlogloss:0.09904
[319]	validation_0-mlogloss:0.09901
[320]	validation_0-mlogloss:0.09896
[321]	validation_0-mlogloss:0.09892
[322]	validation_0-mlogloss:0.09888
[323]	validation_0-mlogloss:0.09885
[324]	validation_0-mlogloss:0.09880
[325]	validation_0-mlogloss:0.09877
[326]	validation_0-mlogloss:0.09873
[327]	validation_0-mlogloss:0.09871
[328]	validation_0-mlogloss:0.09868
[329]	validation_0-mlogloss:0.09864
[330]	validation_0-mlogloss:0.09861
[331]	validation_0-mlogloss:0.09857
[332]	validation_0-mlogloss:0.09855
[333]	validation_0-mlogloss:0.09850
[334]	validation_0-mlogloss:0.09847
[335]	validation_0-mlogloss:0.09844
[336]	validation_0-mlogloss:0.09843
[337]	validation_0-mlogloss:0.09838
[338]	validation_0-mlogloss:0.09836
[339]	validation_0-mlogloss:0.09829
[340]	validation_0-mlogloss:0.09825
[341]	validation_0-mlogloss:0.09822
[342]	validation_0-mlogloss:0.09819
[343]	validation_0-mlogloss:0.09812
[344]	validation_0-mlogloss:0.09810
[345]	validation_0-mlogloss:0.09807
[346]	validation_0-mlogloss:0.09805
[347]	validation_0-mlogloss:0.09800
[348]	validation_0-mlogloss:0.09797
[349]	validation_0-mlogloss:0.09793
[350]	validation_0-mlogloss:0.09786
[351]	validation_0-mlogloss:0.09784
[352]	validation_0-mlogloss:0.09781
[353]	validation_0-mlogloss:0.09775
[354]	validation_0-mlogloss:0.09774
[355]	validation_0-mlogloss:0.09772
[356]	validation_0-mlogloss:0.09769
[357]	validation_0-mlogloss:0.09766
[358]	validation_0-mlogloss:0.09764
[359]	validation_0-mlogloss:0.09760
[360]	validation_0-mlogloss:0.09758
[361]	validation_0-mlogloss:0.09755
[362]	validation_0-mlogloss:0.09752
[363]	validation_0-mlogloss:0.09747
[364]	validation_0-mlogloss:0.09745
[365]	validation_0-mlogloss:0.09743
[366]	validation_0-mlogloss:0.09739
[367]	validation_0-mlogloss:0.09737
[368]	validation_0-mlogloss:0.09733
[369]	validation_0-mlogloss:0.09731
[370]	validation_0-mlogloss:0.09726
[371]	validation_0-mlogloss:0.09723
[372]	validation_0-mlogloss:0.09722
[373]	validation_0-mlogloss:0.09718
[374]	validation_0-mlogloss:0.09717
[375]	validation_0-mlogloss:0.09711
[376]	validation_0-mlogloss:0.09707
[377]	validation_0-mlogloss:0.09703
[378]	validation_0-mlogloss:0.09700
[379]	validation_0-mlogloss:0.09698
[380]	validation_0-mlogloss:0.09694
[381]	validation_0-mlogloss:0.09691
[382]	validation_0-mlogloss:0.09690
[383]	validation_0-mlogloss:0.09687
[384]	validation_0-mlogloss:0.09686
[385]	validation_0-mlogloss:0.09683
[386]	validation_0-mlogloss:0.09683
[387]	validation_0-mlogloss:0.09680
[388]	validation_0-mlogloss:0.09678
[389]	validation_0-mlogloss:0.09675
[390]	validation_0-mlogloss:0.09672
[391]	validation_0-mlogloss:0.09669
[392]	validation_0-mlogloss:0.09667
[393]	validation_0-mlogloss:0.09662
[394]	validation_0-mlogloss:0.09660
[395]	validation_0-mlogloss:0.09657
[396]	validation_0-mlogloss:0.09656
[397]	validation_0-mlogloss:0.09654
[398]	validation_0-mlogloss:0.09653
[399]	validation_0-mlogloss:0.09651
[400]	validation_0-mlogloss:0.09648
[401]	validation_0-mlogloss:0.09644
[402]	validation_0-mlogloss:0.09642
[403]	validation_0-mlogloss:0.09637
[404]	validation_0-mlogloss:0.09634
[405]	validation_0-mlogloss:0.09631
[406]	validation_0-mlogloss:0.09628
[407]	validation_0-mlogloss:0.09626
[408]	validation_0-mlogloss:0.09625
[409]	validation_0-mlogloss:0.09623
[410]	validation_0-mlogloss:0.09620
[411]	validation_0-mlogloss:0.09618
[412]	validation_0-mlogloss:0.09615
[413]	validation_0-mlogloss:0.09614
[414]	validation_0-mlogloss:0.09613
[415]	validation_0-mlogloss:0.09610
[416]	validation_0-mlogloss:0.09609
[417]	validation_0-mlogloss:0.09607
[418]	validation_0-mlogloss:0.09606
[419]	validation_0-mlogloss:0.09605
[420]	validation_0-mlogloss:0.09602
[421]	validation_0-mlogloss:0.09598
[422]	validation_0-mlogloss:0.09596
[423]	validation_0-mlogloss:0.09592
[424]	validation_0-mlogloss:0.09590
[425]	validation_0-mlogloss:0.09589
[426]	validation_0-mlogloss:0.09588
[427]	validation_0-mlogloss:0.09585
[428]	validation_0-mlogloss:0.09582
[429]	validation_0-mlogloss:0.09580
[430]	validation_0-mlogloss:0.09579
[431]	validation_0-mlogloss:0.09578
[432]	validation_0-mlogloss:0.09576
[433]	validation_0-mlogloss:0.09575
[434]	validation_0-mlogloss:0.09572
[435]	validation_0-mlogloss:0.09569
[436]	validation_0-mlogloss:0.09568
[437]	validation_0-mlogloss:0.09568
[438]	validation_0-mlogloss:0.09565
[439]	validation_0-mlogloss:0.09565
[440]	validation_0-mlogloss:0.09564
[441]	validation_0-mlogloss:0.09561
[442]	validation_0-mlogloss:0.09560
[443]	validation_0-mlogloss:0.09555
[444]	validation_0-mlogloss:0.09554
[445]	validation_0-mlogloss:0.09554
[446]	validation_0-mlogloss:0.09553
[447]	validation_0-mlogloss:0.09550
[448]	validation_0-mlogloss:0.09549
[449]	validation_0-mlogloss:0.09549
[450]	validation_0-mlogloss:0.09548
[451]	validation_0-mlogloss:0.09548
[452]	validation_0-mlogloss:0.09545
[453]	validation_0-mlogloss:0.09540
[454]	validation_0-mlogloss:0.09538
[455]	validation_0-mlogloss:0.09534
[456]	validation_0-mlogloss:0.09532
[457]	validation_0-mlogloss:0.09531
[458]	validation_0-mlogloss:0.09529
[459]	validation_0-mlogloss:0.09528
[460]	validation_0-mlogloss:0.09528
[461]	validation_0-mlogloss:0.09526
[462]	validation_0-mlogloss:0.09523
[463]	validation_0-mlogloss:0.09518
[464]	validation_0-mlogloss:0.09517
[465]	validation_0-mlogloss:0.09515
[466]	validation_0-mlogloss:0.09513
[467]	validation_0-mlogloss:0.09512
[468]	validation_0-mlogloss:0.09510
[469]	validation_0-mlogloss:0.09510
[470]	validation_0-mlogloss:0.09507
[471]	validation_0-mlogloss:0.09507
[472]	validation_0-mlogloss:0.09506
[473]	validation_0-mlogloss:0.09505
[474]	validation_0-mlogloss:0.09504
[475]	validation_0-mlogloss:0.09502
[476]	validation_0-mlogloss:0.09500
[477]	validation_0-mlogloss:0.09498
[478]	validation_0-mlogloss:0.09496
[479]	validation_0-mlogloss:0.09496
[480]	validation_0-mlogloss:0.09495
[481]	validation_0-mlogloss:0.09494
[482]	validation_0-mlogloss:0.09493
[483]	validation_0-mlogloss:0.09491
[484]	validation_0-mlogloss:0.09488
[485]	validation_0-mlogloss:0.09486
[486]	validation_0-mlogloss:0.09485
[487]	validation_0-mlogloss:0.09484
[488]	validation_0-mlogloss:0.09483
[489]	validation_0-mlogloss:0.09482
[490]	validation_0-mlogloss:0.09480
[491]	validation_0-mlogloss:0.09479
[492]	validation_0-mlogloss:0.09477
[493]	validation_0-mlogloss:0.09477
[494]	validation_0-mlogloss:0.09475
[495]	validation_0-mlogloss:0.09474
[496]	validation_0-mlogloss:0.09473
[497]	validation_0-mlogloss:0.09472
[498]	validation_0-mlogloss:0.09471
[499]	validation_0-mlogloss:0.09470
[500]	validation_0-mlogloss:0.09469
[501]	validation_0-mlogloss:0.09467
[502]	validation_0-mlogloss:0.09466
[503]	validation_0-mlogloss:0.09465
[504]	validation_0-mlogloss:0.09464
[505]	validation_0-mlogloss:0.09462
[506]	validation_0-mlogloss:0.09462
[507]	validation_0-mlogloss:0.09461
[508]	validation_0-mlogloss:0.09460
[509]	validation_0-mlogloss:0.09459
[510]	validation_0-mlogloss:0.09459
[511]	validation_0-mlogloss:0.09458
[512]	validation_0-mlogloss:0.09458
[513]	validation_0-mlogloss:0.09457
[514]	validation_0-mlogloss:0.09453
[515]	validation_0-mlogloss:0.09451
[516]	validation_0-mlogloss:0.09450
[517]	validation_0-mlogloss:0.09450
[518]	validation_0-mlogloss:0.09449
[519]	validation_0-mlogloss:0.09447
[520]	validation_0-mlogloss:0.09445
[521]	validation_0-mlogloss:0.09445
[522]	validation_0-mlogloss:0.09444
[523]	validation_0-mlogloss:0.09444
[524]	validation_0-mlogloss:0.09443
[525]	validation_0-mlogloss:0.09441
[526]	validation_0-mlogloss:0.09439
[527]	validation_0-mlogloss:0.09438
[528]	validation_0-mlogloss:0.09437
[529]	validation_0-mlogloss:0.09434
[530]	validation_0-mlogloss:0.09432
[531]	validation_0-mlogloss:0.09429
[532]	validation_0-mlogloss:0.09426
[533]	validation_0-mlogloss:0.09424
[534]	validation_0-mlogloss:0.09420
[535]	validation_0-mlogloss:0.09418
[536]	validation_0-mlogloss:0.09416
[537]	validation_0-mlogloss:0.09416
[538]	validation_0-mlogloss:0.09414
[539]	validation_0-mlogloss:0.09412
[540]	validation_0-mlogloss:0.09412
[541]	validation_0-mlogloss:0.09409
[542]	validation_0-mlogloss:0.09408
[543]	validation_0-mlogloss:0.09407
[544]	validation_0-mlogloss:0.09404
[545]	validation_0-mlogloss:0.09403
[546]	validation_0-mlogloss:0.09403
[547]	validation_0-mlogloss:0.09401
[548]	validation_0-mlogloss:0.09400
[549]	validation_0-mlogloss:0.09396
[550]	validation_0-mlogloss:0.09395
[551]	validation_0-mlogloss:0.09394
[552]	validation_0-mlogloss:0.09390
[553]	validation_0-mlogloss:0.09388
[554]	validation_0-mlogloss:0.09385
[555]	validation_0-mlogloss:0.09384
[556]	validation_0-mlogloss:0.09383
[557]	validation_0-mlogloss:0.09379

/home/jonanakai/miniconda3/envs/ds/lib/python3.12/site-packages/xgboost/core.py:751: UserWarning: [13:17:10] WARNING: /__w/xgboost/xgboost/src/common/error_msg.cc:62: Falling back to prediction using DMatrix due to mismatched devices. This might lead to higher memory usage and slower performance. XGBoost is running on: cuda:0, while the input data is on: cpu.
Potential solutions:
- Use a data structure that matches the device ordinal in the booster.
- Set the device for booster before call to inplace_predict.

This warning will only be shown once.

  return func(**kwargs)

Accuracy: 0.9676972373776739
              precision    recall  f1-score   support

      GALAXY       0.98      0.98      0.98     75496
         QSO       0.97      0.96      0.96     23429
        STAR       0.93      0.92      0.93     16545

    accuracy                           0.97    115470
   macro avg       0.96      0.96      0.96    115470
weighted avg       0.97      0.97      0.97    115470

In [14]:
test = pd.read_csv("../Data/test.csv", index_col="id")

test = add_features(test)
for col in categorical_cols:
    test[col] = test[col].astype("category")

test_preds = model.predict(test)
test_pred_labels = le.inverse_transform(test_preds)

submission = pd.DataFrame({
    "id": test.index,
    "class": test_pred_labels
})

submission.to_csv("../Data/submission_xgboost_v2.csv", index=False)

submission.head()

       id   class
0  577347  GALAXY
1  577348  GALAXY
2  577349  GALAXY
3  577350    STAR
4  577351  GALAXY