## XGBoost v1

- No data preprocessing
- No model tweaking/optimization, only a basic implementation of XGBoost
- Baseline XGBoost model

In [1]:
from dotenv import load_dotenv
import kagglehub
from pathlib import Path
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report
import torch
from xgboost import XGBClassifier

if torch.cuda.is_available():
    device="cuda"
else:
    device="cpu"
device

'cuda'

In [2]:
load_dotenv()

if not Path("../Data/.complete/competitions/playground-series-s6e6/bundle.complete").is_file():
    kagglehub.competition_download("playground-series-s6e6", output_dir="Data")
    print("Data downloaded")
else:
    print("Data not downloaded, already exists")

Data not downloaded, already exists

In [3]:
train = pd.read_csv("../Data/train.csv", index_col="id")
train.head()

,alpha,delta,u,g,r,i,z,redshift,spectral_type,galaxy_population,class
id,,,,,,,,,,,
0,147.734256,16.959273,25.472123,21.895559,20.357926,19.257113,18.621057,0.408982,M,Red_Sequence,GALAXY
1,127.988677,32.346716,20.778509,19.087062,17.587208,17.226067,16.786433,0.157976,M,Red_Sequence,GALAXY
2,179.792648,35.344843,21.035203,21.079128,21.171840,20.582629,20.557366,2.823770,O/B,Blue_Cloud,QSO
3,225.818295,48.569421,23.305056,21.050736,19.017754,18.365658,17.914952,0.536099,M,Red_Sequence,GALAXY
4,141.836135,19.342852,21.703158,19.471680,18.234449,17.899447,17.616185,0.555761,M,Red_Sequence,GALAXY

In [4]:
train.dtypes

alpha                float64
delta                float64
u                    float64
g                    float64
r                    float64
i                    float64
z                    float64
redshift             float64
spectral_type         object
galaxy_population     object
class                 object
dtype: object

In [5]:
X = train.drop(columns=["class"])
categorical_cols = ["spectral_type", "galaxy_population"]
for col in categorical_cols:
    X[col] = X[col].astype("category")

le = LabelEncoder()
y = le.fit_transform(train["class"])

X_train, X_val, y_train, y_val = train_test_split(
    X, 
    y, 
    test_size=0.2,
    random_state=42, 
    stratify=y
)

In [6]:
model = XGBClassifier(
    device=device,
    random_state=42,
    n_estimators=2000,
    learning_rate=0.05,
    max_depth=5,
    early_stopping_rounds=100,
    enable_categorical=True,
    verbosity=0
)

model.fit(
    X_train,
    y_train,
    eval_set=[(X_val, y_val)]
)

preds = model.predict(X_val)

print("Accuracy:", accuracy_score(y_val, preds))
print(classification_report(y_val, preds, target_names=le.classes_))

[0]	validation_0-mlogloss:0.82304
[1]	validation_0-mlogloss:0.77355
[2]	validation_0-mlogloss:0.72976
[3]	validation_0-mlogloss:0.69068
[4]	validation_0-mlogloss:0.65540
[5]	validation_0-mlogloss:0.62336
[6]	validation_0-mlogloss:0.59424

sh: 1: nvidia-smi: not found

[7]	validation_0-mlogloss:0.56737
[8]	validation_0-mlogloss:0.54269
[9]	validation_0-mlogloss:0.51991
[10]	validation_0-mlogloss:0.49863
[11]	validation_0-mlogloss:0.47904
[12]	validation_0-mlogloss:0.46065
[13]	validation_0-mlogloss:0.44358
[14]	validation_0-mlogloss:0.42750
[15]	validation_0-mlogloss:0.41249
[16]	validation_0-mlogloss:0.39845
[17]	validation_0-mlogloss:0.38534
[18]	validation_0-mlogloss:0.37304
[19]	validation_0-mlogloss:0.36141
[20]	validation_0-mlogloss:0.35055
[21]	validation_0-mlogloss:0.34016
[22]	validation_0-mlogloss:0.33048
[23]	validation_0-mlogloss:0.32133
[24]	validation_0-mlogloss:0.31271
[25]	validation_0-mlogloss:0.30456
[26]	validation_0-mlogloss:0.29683
[27]	validation_0-mlogloss:0.28951
[28]	validation_0-mlogloss:0.28256
[29]	validation_0-mlogloss:0.27596
[30]	validation_0-mlogloss:0.26971
[31]	validation_0-mlogloss:0.26371
[32]	validation_0-mlogloss:0.25810
[33]	validation_0-mlogloss:0.25279
[34]	validation_0-mlogloss:0.24767
[35]	validation_0-mlogloss:0.24292
[36]	validation_0-mlogloss:0.23831
[37]	validation_0-mlogloss:0.23396
[38]	validation_0-mlogloss:0.22988
[39]	validation_0-mlogloss:0.22590
[40]	validation_0-mlogloss:0.22212
[41]	validation_0-mlogloss:0.21853
[42]	validation_0-mlogloss:0.21511
[43]	validation_0-mlogloss:0.21187
[44]	validation_0-mlogloss:0.20876
[45]	validation_0-mlogloss:0.20582
[46]	validation_0-mlogloss:0.20294
[47]	validation_0-mlogloss:0.20027
[48]	validation_0-mlogloss:0.19768
[49]	validation_0-mlogloss:0.19517
[50]	validation_0-mlogloss:0.19284
[51]	validation_0-mlogloss:0.19045
[52]	validation_0-mlogloss:0.18823
[53]	validation_0-mlogloss:0.18608
[54]	validation_0-mlogloss:0.18401
[55]	validation_0-mlogloss:0.18211
[56]	validation_0-mlogloss:0.18024
[57]	validation_0-mlogloss:0.17835
[58]	validation_0-mlogloss:0.17663
[59]	validation_0-mlogloss:0.17482
[60]	validation_0-mlogloss:0.17314
[61]	validation_0-mlogloss:0.17162
[62]	validation_0-mlogloss:0.17007
[63]	validation_0-mlogloss:0.16864
[64]	validation_0-mlogloss:0.16722
[65]	validation_0-mlogloss:0.16589
[66]	validation_0-mlogloss:0.16460
[67]	validation_0-mlogloss:0.16344
[68]	validation_0-mlogloss:0.16225
[69]	validation_0-mlogloss:0.16111
[70]	validation_0-mlogloss:0.16001
[71]	validation_0-mlogloss:0.15897
[72]	validation_0-mlogloss:0.15802
[73]	validation_0-mlogloss:0.15710
[74]	validation_0-mlogloss:0.15621
[75]	validation_0-mlogloss:0.15538
[76]	validation_0-mlogloss:0.15463
[77]	validation_0-mlogloss:0.15381
[78]	validation_0-mlogloss:0.15306
[79]	validation_0-mlogloss:0.15218
[80]	validation_0-mlogloss:0.15152
[81]	validation_0-mlogloss:0.15071
[82]	validation_0-mlogloss:0.15007
[83]	validation_0-mlogloss:0.14935
[84]	validation_0-mlogloss:0.14864
[85]	validation_0-mlogloss:0.14806
[86]	validation_0-mlogloss:0.14735
[87]	validation_0-mlogloss:0.14677
[88]	validation_0-mlogloss:0.14612
[89]	validation_0-mlogloss:0.14560
[90]	validation_0-mlogloss:0.14505
[91]	validation_0-mlogloss:0.14449
[92]	validation_0-mlogloss:0.14403
[93]	validation_0-mlogloss:0.14346
[94]	validation_0-mlogloss:0.14300
[95]	validation_0-mlogloss:0.14246
[96]	validation_0-mlogloss:0.14201
[97]	validation_0-mlogloss:0.14160
[98]	validation_0-mlogloss:0.14111
[99]	validation_0-mlogloss:0.14056
[100]	validation_0-mlogloss:0.14021
[101]	validation_0-mlogloss:0.13970
[102]	validation_0-mlogloss:0.13924
[103]	validation_0-mlogloss:0.13889
[104]	validation_0-mlogloss:0.13854
[105]	validation_0-mlogloss:0.13818
[106]	validation_0-mlogloss:0.13781
[107]	validation_0-mlogloss:0.13733
[108]	validation_0-mlogloss:0.13701
[109]	validation_0-mlogloss:0.13663
[110]	validation_0-mlogloss:0.13616
[111]	validation_0-mlogloss:0.13574
[112]	validation_0-mlogloss:0.13541
[113]	validation_0-mlogloss:0.13504
[114]	validation_0-mlogloss:0.13467
[115]	validation_0-mlogloss:0.13437
[116]	validation_0-mlogloss:0.13410
[117]	validation_0-mlogloss:0.13377
[118]	validation_0-mlogloss:0.13349
[119]	validation_0-mlogloss:0.13317
[120]	validation_0-mlogloss:0.13290
[121]	validation_0-mlogloss:0.13265
[122]	validation_0-mlogloss:0.13240
[123]	validation_0-mlogloss:0.13210
[124]	validation_0-mlogloss:0.13180
[125]	validation_0-mlogloss:0.13158
[126]	validation_0-mlogloss:0.13128
[127]	validation_0-mlogloss:0.13104
[128]	validation_0-mlogloss:0.13081
[129]	validation_0-mlogloss:0.13053
[130]	validation_0-mlogloss:0.13024
[131]	validation_0-mlogloss:0.13000
[132]	validation_0-mlogloss:0.12972
[133]	validation_0-mlogloss:0.12951
[134]	validation_0-mlogloss:0.12930
[135]	validation_0-mlogloss:0.12911
[136]	validation_0-mlogloss:0.12886
[137]	validation_0-mlogloss:0.12866
[138]	validation_0-mlogloss:0.12849
[139]	validation_0-mlogloss:0.12825
[140]	validation_0-mlogloss:0.12799
[141]	validation_0-mlogloss:0.12774
[142]	validation_0-mlogloss:0.12746
[143]	validation_0-mlogloss:0.12726
[144]	validation_0-mlogloss:0.12709
[145]	validation_0-mlogloss:0.12687
[146]	validation_0-mlogloss:0.12665
[147]	validation_0-mlogloss:0.12639
[148]	validation_0-mlogloss:0.12619
[149]	validation_0-mlogloss:0.12604
[150]	validation_0-mlogloss:0.12576
[151]	validation_0-mlogloss:0.12558
[152]	validation_0-mlogloss:0.12539
[153]	validation_0-mlogloss:0.12514
[154]	validation_0-mlogloss:0.12497
[155]	validation_0-mlogloss:0.12478
[156]	validation_0-mlogloss:0.12460
[157]	validation_0-mlogloss:0.12439
[158]	validation_0-mlogloss:0.12420
[159]	validation_0-mlogloss:0.12409
[160]	validation_0-mlogloss:0.12387
[161]	validation_0-mlogloss:0.12374
[162]	validation_0-mlogloss:0.12359
[163]	validation_0-mlogloss:0.12336
[164]	validation_0-mlogloss:0.12320
[165]	validation_0-mlogloss:0.12300
[166]	validation_0-mlogloss:0.12283
[167]	validation_0-mlogloss:0.12263
[168]	validation_0-mlogloss:0.12247
[169]	validation_0-mlogloss:0.12226
[170]	validation_0-mlogloss:0.12211
[171]	validation_0-mlogloss:0.12200
[172]	validation_0-mlogloss:0.12185
[173]	validation_0-mlogloss:0.12173
[174]	validation_0-mlogloss:0.12158
[175]	validation_0-mlogloss:0.12146
[176]	validation_0-mlogloss:0.12130
[177]	validation_0-mlogloss:0.12116
[178]	validation_0-mlogloss:0.12104
[179]	validation_0-mlogloss:0.12090
[180]	validation_0-mlogloss:0.12080
[181]	validation_0-mlogloss:0.12063
[182]	validation_0-mlogloss:0.12050
[183]	validation_0-mlogloss:0.12040
[184]	validation_0-mlogloss:0.12021
[185]	validation_0-mlogloss:0.12006
[186]	validation_0-mlogloss:0.11998
[187]	validation_0-mlogloss:0.11983
[188]	validation_0-mlogloss:0.11974
[189]	validation_0-mlogloss:0.11962
[190]	validation_0-mlogloss:0.11948
[191]	validation_0-mlogloss:0.11935
[192]	validation_0-mlogloss:0.11923
[193]	validation_0-mlogloss:0.11913
[194]	validation_0-mlogloss:0.11901
[195]	validation_0-mlogloss:0.11891
[196]	validation_0-mlogloss:0.11881
[197]	validation_0-mlogloss:0.11869
[198]	validation_0-mlogloss:0.11860
[199]	validation_0-mlogloss:0.11848
[200]	validation_0-mlogloss:0.11838
[201]	validation_0-mlogloss:0.11826
[202]	validation_0-mlogloss:0.11816
[203]	validation_0-mlogloss:0.11807
[204]	validation_0-mlogloss:0.11798
[205]	validation_0-mlogloss:0.11786
[206]	validation_0-mlogloss:0.11777
[207]	validation_0-mlogloss:0.11771
[208]	validation_0-mlogloss:0.11763
[209]	validation_0-mlogloss:0.11750
[210]	validation_0-mlogloss:0.11744
[211]	validation_0-mlogloss:0.11733
[212]	validation_0-mlogloss:0.11724
[213]	validation_0-mlogloss:0.11712
[214]	validation_0-mlogloss:0.11705
[215]	validation_0-mlogloss:0.11693
[216]	validation_0-mlogloss:0.11681
[217]	validation_0-mlogloss:0.11667
[218]	validation_0-mlogloss:0.11655
[219]	validation_0-mlogloss:0.11639
[220]	validation_0-mlogloss:0.11625
[221]	validation_0-mlogloss:0.11613
[222]	validation_0-mlogloss:0.11601
[223]	validation_0-mlogloss:0.11592
[224]	validation_0-mlogloss:0.11577
[225]	validation_0-mlogloss:0.11566
[226]	validation_0-mlogloss:0.11557
[227]	validation_0-mlogloss:0.11543
[228]	validation_0-mlogloss:0.11529
[229]	validation_0-mlogloss:0.11511
[230]	validation_0-mlogloss:0.11499
[231]	validation_0-mlogloss:0.11490
[232]	validation_0-mlogloss:0.11476
[233]	validation_0-mlogloss:0.11466
[234]	validation_0-mlogloss:0.11454
[235]	validation_0-mlogloss:0.11447
[236]	validation_0-mlogloss:0.11437
[237]	validation_0-mlogloss:0.11427
[238]	validation_0-mlogloss:0.11417
[239]	validation_0-mlogloss:0.11407
[240]	validation_0-mlogloss:0.11401
[241]	validation_0-mlogloss:0.11389
[242]	validation_0-mlogloss:0.11378
[243]	validation_0-mlogloss:0.11371
[244]	validation_0-mlogloss:0.11362
[245]	validation_0-mlogloss:0.11354
[246]	validation_0-mlogloss:0.11352
[247]	validation_0-mlogloss:0.11343
[248]	validation_0-mlogloss:0.11334
[249]	validation_0-mlogloss:0.11329
[250]	validation_0-mlogloss:0.11320
[251]	validation_0-mlogloss:0.11314
[252]	validation_0-mlogloss:0.11303
[253]	validation_0-mlogloss:0.11299
[254]	validation_0-mlogloss:0.11289
[255]	validation_0-mlogloss:0.11281
[256]	validation_0-mlogloss:0.11271
[257]	validation_0-mlogloss:0.11264
[258]	validation_0-mlogloss:0.11256
[259]	validation_0-mlogloss:0.11248
[260]	validation_0-mlogloss:0.11239
[261]	validation_0-mlogloss:0.11232
[262]	validation_0-mlogloss:0.11223
[263]	validation_0-mlogloss:0.11216
[264]	validation_0-mlogloss:0.11210
[265]	validation_0-mlogloss:0.11202
[266]	validation_0-mlogloss:0.11194
[267]	validation_0-mlogloss:0.11185
[268]	validation_0-mlogloss:0.11178
[269]	validation_0-mlogloss:0.11172
[270]	validation_0-mlogloss:0.11161
[271]	validation_0-mlogloss:0.11152
[272]	validation_0-mlogloss:0.11142
[273]	validation_0-mlogloss:0.11139
[274]	validation_0-mlogloss:0.11130
[275]	validation_0-mlogloss:0.11122
[276]	validation_0-mlogloss:0.11117
[277]	validation_0-mlogloss:0.11111
[278]	validation_0-mlogloss:0.11103
[279]	validation_0-mlogloss:0.11096
[280]	validation_0-mlogloss:0.11090
[281]	validation_0-mlogloss:0.11086
[282]	validation_0-mlogloss:0.11080
[283]	validation_0-mlogloss:0.11072
[284]	validation_0-mlogloss:0.11064
[285]	validation_0-mlogloss:0.11057
[286]	validation_0-mlogloss:0.11049
[287]	validation_0-mlogloss:0.11042
[288]	validation_0-mlogloss:0.11036
[289]	validation_0-mlogloss:0.11031
[290]	validation_0-mlogloss:0.11027
[291]	validation_0-mlogloss:0.11018
[292]	validation_0-mlogloss:0.11008
[293]	validation_0-mlogloss:0.11001
[294]	validation_0-mlogloss:0.10995
[295]	validation_0-mlogloss:0.10989
[296]	validation_0-mlogloss:0.10984
[297]	validation_0-mlogloss:0.10980
[298]	validation_0-mlogloss:0.10974
[299]	validation_0-mlogloss:0.10965
[300]	validation_0-mlogloss:0.10958
[301]	validation_0-mlogloss:0.10954
[302]	validation_0-mlogloss:0.10950
[303]	validation_0-mlogloss:0.10942
[304]	validation_0-mlogloss:0.10936
[305]	validation_0-mlogloss:0.10931
[306]	validation_0-mlogloss:0.10926
[307]	validation_0-mlogloss:0.10922
[308]	validation_0-mlogloss:0.10916
[309]	validation_0-mlogloss:0.10908
[310]	validation_0-mlogloss:0.10903
[311]	validation_0-mlogloss:0.10899
[312]	validation_0-mlogloss:0.10891
[313]	validation_0-mlogloss:0.10884
[314]	validation_0-mlogloss:0.10877
[315]	validation_0-mlogloss:0.10873
[316]	validation_0-mlogloss:0.10865
[317]	validation_0-mlogloss:0.10860
[318]	validation_0-mlogloss:0.10854
[319]	validation_0-mlogloss:0.10847
[320]	validation_0-mlogloss:0.10839
[321]	validation_0-mlogloss:0.10831
[322]	validation_0-mlogloss:0.10826
[323]	validation_0-mlogloss:0.10821
[324]	validation_0-mlogloss:0.10815
[325]	validation_0-mlogloss:0.10807
[326]	validation_0-mlogloss:0.10802
[327]	validation_0-mlogloss:0.10797
[328]	validation_0-mlogloss:0.10790
[329]	validation_0-mlogloss:0.10784
[330]	validation_0-mlogloss:0.10776
[331]	validation_0-mlogloss:0.10769
[332]	validation_0-mlogloss:0.10765
[333]	validation_0-mlogloss:0.10761
[334]	validation_0-mlogloss:0.10754
[335]	validation_0-mlogloss:0.10750
[336]	validation_0-mlogloss:0.10745
[337]	validation_0-mlogloss:0.10740
[338]	validation_0-mlogloss:0.10734
[339]	validation_0-mlogloss:0.10728
[340]	validation_0-mlogloss:0.10721
[341]	validation_0-mlogloss:0.10715
[342]	validation_0-mlogloss:0.10711
[343]	validation_0-mlogloss:0.10707
[344]	validation_0-mlogloss:0.10700
[345]	validation_0-mlogloss:0.10694
[346]	validation_0-mlogloss:0.10690
[347]	validation_0-mlogloss:0.10686
[348]	validation_0-mlogloss:0.10683
[349]	validation_0-mlogloss:0.10679
[350]	validation_0-mlogloss:0.10675
[351]	validation_0-mlogloss:0.10671
[352]	validation_0-mlogloss:0.10664
[353]	validation_0-mlogloss:0.10658
[354]	validation_0-mlogloss:0.10654
[355]	validation_0-mlogloss:0.10647
[356]	validation_0-mlogloss:0.10640
[357]	validation_0-mlogloss:0.10636
[358]	validation_0-mlogloss:0.10630
[359]	validation_0-mlogloss:0.10626
[360]	validation_0-mlogloss:0.10618
[361]	validation_0-mlogloss:0.10614
[362]	validation_0-mlogloss:0.10612
[363]	validation_0-mlogloss:0.10610
[364]	validation_0-mlogloss:0.10606
[365]	validation_0-mlogloss:0.10603
[366]	validation_0-mlogloss:0.10597
[367]	validation_0-mlogloss:0.10593
[368]	validation_0-mlogloss:0.10590
[369]	validation_0-mlogloss:0.10588
[370]	validation_0-mlogloss:0.10587
[371]	validation_0-mlogloss:0.10583
[372]	validation_0-mlogloss:0.10580
[373]	validation_0-mlogloss:0.10575
[374]	validation_0-mlogloss:0.10571
[375]	validation_0-mlogloss:0.10566
[376]	validation_0-mlogloss:0.10562
[377]	validation_0-mlogloss:0.10559
[378]	validation_0-mlogloss:0.10555
[379]	validation_0-mlogloss:0.10553
[380]	validation_0-mlogloss:0.10550
[381]	validation_0-mlogloss:0.10548
[382]	validation_0-mlogloss:0.10544
[383]	validation_0-mlogloss:0.10540
[384]	validation_0-mlogloss:0.10535
[385]	validation_0-mlogloss:0.10531
[386]	validation_0-mlogloss:0.10528
[387]	validation_0-mlogloss:0.10526
[388]	validation_0-mlogloss:0.10521
[389]	validation_0-mlogloss:0.10515
[390]	validation_0-mlogloss:0.10511
[391]	validation_0-mlogloss:0.10505
[392]	validation_0-mlogloss:0.10503
[393]	validation_0-mlogloss:0.10499
[394]	validation_0-mlogloss:0.10492
[395]	validation_0-mlogloss:0.10490
[396]	validation_0-mlogloss:0.10486
[397]	validation_0-mlogloss:0.10479
[398]	validation_0-mlogloss:0.10475
[399]	validation_0-mlogloss:0.10470
[400]	validation_0-mlogloss:0.10466
[401]	validation_0-mlogloss:0.10464
[402]	validation_0-mlogloss:0.10460
[403]	validation_0-mlogloss:0.10457
[404]	validation_0-mlogloss:0.10453
[405]	validation_0-mlogloss:0.10449
[406]	validation_0-mlogloss:0.10446
[407]	validation_0-mlogloss:0.10441
[408]	validation_0-mlogloss:0.10440
[409]	validation_0-mlogloss:0.10436
[410]	validation_0-mlogloss:0.10431
[411]	validation_0-mlogloss:0.10429
[412]	validation_0-mlogloss:0.10426
[413]	validation_0-mlogloss:0.10424
[414]	validation_0-mlogloss:0.10421
[415]	validation_0-mlogloss:0.10418
[416]	validation_0-mlogloss:0.10414
[417]	validation_0-mlogloss:0.10412
[418]	validation_0-mlogloss:0.10408
[419]	validation_0-mlogloss:0.10404
[420]	validation_0-mlogloss:0.10401
[421]	validation_0-mlogloss:0.10397
[422]	validation_0-mlogloss:0.10391
[423]	validation_0-mlogloss:0.10387
[424]	validation_0-mlogloss:0.10384
[425]	validation_0-mlogloss:0.10380
[426]	validation_0-mlogloss:0.10377
[427]	validation_0-mlogloss:0.10372
[428]	validation_0-mlogloss:0.10364
[429]	validation_0-mlogloss:0.10360
[430]	validation_0-mlogloss:0.10357
[431]	validation_0-mlogloss:0.10354
[432]	validation_0-mlogloss:0.10351
[433]	validation_0-mlogloss:0.10348
[434]	validation_0-mlogloss:0.10344
[435]	validation_0-mlogloss:0.10341
[436]	validation_0-mlogloss:0.10339
[437]	validation_0-mlogloss:0.10336
[438]	validation_0-mlogloss:0.10332
[439]	validation_0-mlogloss:0.10329
[440]	validation_0-mlogloss:0.10325
[441]	validation_0-mlogloss:0.10323
[442]	validation_0-mlogloss:0.10320
[443]	validation_0-mlogloss:0.10316
[444]	validation_0-mlogloss:0.10312
[445]	validation_0-mlogloss:0.10307
[446]	validation_0-mlogloss:0.10304
[447]	validation_0-mlogloss:0.10301
[448]	validation_0-mlogloss:0.10300
[449]	validation_0-mlogloss:0.10296
[450]	validation_0-mlogloss:0.10293
[451]	validation_0-mlogloss:0.10290
[452]	validation_0-mlogloss:0.10287
[453]	validation_0-mlogloss:0.10286
[454]	validation_0-mlogloss:0.10283
[455]	validation_0-mlogloss:0.10280
[456]	validation_0-mlogloss:0.10277
[457]	validation_0-mlogloss:0.10275
[458]	validation_0-mlogloss:0.10273
[459]	validation_0-mlogloss:0.10268
[460]	validation_0-mlogloss:0.10265
[461]	validation_0-mlogloss:0.10262
[462]	validation_0-mlogloss:0.10261
[463]	validation_0-mlogloss:0.10257
[464]	validation_0-mlogloss:0.10254
[465]	validation_0-mlogloss:0.10250
[466]	validation_0-mlogloss:0.10249
[467]	validation_0-mlogloss:0.10247
[468]	validation_0-mlogloss:0.10243
[469]	validation_0-mlogloss:0.10241
[470]	validation_0-mlogloss:0.10240
[471]	validation_0-mlogloss:0.10239
[472]	validation_0-mlogloss:0.10236
[473]	validation_0-mlogloss:0.10231
[474]	validation_0-mlogloss:0.10229
[475]	validation_0-mlogloss:0.10224
[476]	validation_0-mlogloss:0.10221
[477]	validation_0-mlogloss:0.10218
[478]	validation_0-mlogloss:0.10214
[479]	validation_0-mlogloss:0.10211
[480]	validation_0-mlogloss:0.10208
[481]	validation_0-mlogloss:0.10202
[482]	validation_0-mlogloss:0.10198
[483]	validation_0-mlogloss:0.10196
[484]	validation_0-mlogloss:0.10193
[485]	validation_0-mlogloss:0.10189
[486]	validation_0-mlogloss:0.10187
[487]	validation_0-mlogloss:0.10183
[488]	validation_0-mlogloss:0.10179
[489]	validation_0-mlogloss:0.10174
[490]	validation_0-mlogloss:0.10172
[491]	validation_0-mlogloss:0.10170
[492]	validation_0-mlogloss:0.10168
[493]	validation_0-mlogloss:0.10165
[494]	validation_0-mlogloss:0.10164
[495]	validation_0-mlogloss:0.10161
[496]	validation_0-mlogloss:0.10157
[497]	validation_0-mlogloss:0.10155
[498]	validation_0-mlogloss:0.10153
[499]	validation_0-mlogloss:0.10149
[500]	validation_0-mlogloss:0.10145
[501]	validation_0-mlogloss:0.10145
[502]	validation_0-mlogloss:0.10143
[503]	validation_0-mlogloss:0.10139
[504]	validation_0-mlogloss:0.10136
[505]	validation_0-mlogloss:0.10134
[506]	validation_0-mlogloss:0.10132
[507]	validation_0-mlogloss:0.10131
[508]	validation_0-mlogloss:0.10129
[509]	validation_0-mlogloss:0.10127
[510]	validation_0-mlogloss:0.10123
[511]	validation_0-mlogloss:0.10121
[512]	validation_0-mlogloss:0.10117
[513]	validation_0-mlogloss:0.10115
[514]	validation_0-mlogloss:0.10113
[515]	validation_0-mlogloss:0.10110
[516]	validation_0-mlogloss:0.10109
[517]	validation_0-mlogloss:0.10105
[518]	validation_0-mlogloss:0.10103
[519]	validation_0-mlogloss:0.10102
[520]	validation_0-mlogloss:0.10099
[521]	validation_0-mlogloss:0.10097
[522]	validation_0-mlogloss:0.10096
[523]	validation_0-mlogloss:0.10093
[524]	validation_0-mlogloss:0.10091
[525]	validation_0-mlogloss:0.10090
[526]	validation_0-mlogloss:0.10086
[527]	validation_0-mlogloss:0.10084
[528]	validation_0-mlogloss:0.10082
[529]	validation_0-mlogloss:0.10079
[530]	validation_0-mlogloss:0.10077
[531]	validation_0-mlogloss:0.10076
[532]	validation_0-mlogloss:0.10075
[533]	validation_0-mlogloss:0.10071
[534]	validation_0-mlogloss:0.10069
[535]	validation_0-mlogloss:0.10067
[536]	validation_0-mlogloss:0.10065
[537]	validation_0-mlogloss:0.10062
[538]	validation_0-mlogloss:0.10059
[539]	validation_0-mlogloss:0.10056
[540]	validation_0-mlogloss:0.10054
[541]	validation_0-mlogloss:0.10052
[542]	validation_0-mlogloss:0.10051
[543]	validation_0-mlogloss:0.10048
[544]	validation_0-mlogloss:0.10043
[545]	validation_0-mlogloss:0.10041
[546]	validation_0-mlogloss:0.10040
[547]	validation_0-mlogloss:0.10034
[548]	validation_0-mlogloss:0.10031
[549]	validation_0-mlogloss:0.10026
[550]	validation_0-mlogloss:0.10024
[551]	validation_0-mlogloss:0.10021
[552]	validation_0-mlogloss:0.10019
[553]	validation_0-mlogloss:0.10018
[554]	validation_0-mlogloss:0.10015
[555]	validation_0-mlogloss:0.10012
[556]	validation_0-mlogloss:0.10010
[557]	validation_0-mlogloss:0.10007
[558]	validation_0-mlogloss:0.10005
[559]	validation_0-mlogloss:0.10004
[560]	validation_0-mlogloss:0.10001
[561]	validation_0-mlogloss:0.09995
[562]	validation_0-mlogloss:0.09993
[563]	validation_0-mlogloss:0.09990
[564]	validation_0-mlogloss:0.09988

In [7]:
test = pd.read_csv("../Data/test.csv", index_col="id")

for col in categorical_cols:
    test[col] = test[col].astype("category")

test_preds = model.predict(test)
test_pred_labels = le.inverse_transform(test_preds)

submission = pd.DataFrame({
    "id": test.index,
    "class": test_pred_labels
})

submission.to_csv("../Data/submission_xgboost_v1.csv", index=False)

submission.head()

       id   class
0  577347  GALAXY
1  577348  GALAXY
2  577349  GALAXY
3  577350    STAR
4  577351  GALAXY